language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

install:
  - curl -fsS -o get-poetry.py https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
  - python get-poetry.py --preview -y
  - source $HOME/.poetry/env
  - poetry install --extras memcached

script: poetry run pytest tests/

services:
  - memcached
