language: python
arch:
  - amd64
  - arm64

python: 3.6
cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

install:
  - curl -fsS -o get-poetry.py https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
  - python get-poetry.py --preview -y
  - source $HOME/.poetry/env
  - poetry install --extras memcached

script: poetry run pytest tests/

services:
  - memcached
