language: python
arch:
  - amd64
  - arm64

python:
  - "3.6"
  - "3.8"
cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

install:
  # `- pip install fakeredis
  - curl -fsS -o get-poetry.py https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
  - python get-poetry.py --preview -y
  - source $HOME/.poetry/env
  - poetry install
  #--extras memcached

script: python -m pytest tests/

services:
  - memcached
